### register client
## PT1H 1 hour in ISO-8601 duration format
## P30D 30 days in ISO-8601 duration format
POST http://localhost:9000/oauth2/register
Authorization: Bearer {{$auth.token("auth-registrar")}}
content-type: application/json

{
  "clientId": "spa-client",
  "clientSecret": "spa-secret",
  "clientName": "Spa Client",
  "authorizationGrantTypes": [
    "authorization_code"
  ],
  "authenticationMethods": [
    "none"
  ],
  "redirectUris": [
    "http://localhost:4200/callback"
  ],
  "scopes": [
    "openid"
  ],
  "clientSettings": {
    "requireAuthorizationConsent": true,
    "requireProofKey": true
  },
  "tokenSettings": {
    "accessTokenTimeToLive": "PT1H",
    "refreshTokenTimeToLive": "P30D"
  }
}

### Save user
POST http://localhost:9000/api/users
Authorization: Bearer {{$auth.token("auth-example-client")}}
content-type: application/json

{
  "username": "teundeclercq",
  "password": "password!23",
  "roles": [
    {
      "name": "create"
    }
  ]
}

###
POST http://localhost:9000/oauth2/token
Authorization: Bearer {{$auth.token("auth-example-client")}}
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
    &username=teundeclercq
    &password=password!23
    &scope=user:manage


###
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
    &client_id=example-client
    &client_secret=example-secret
    &redirect_uri=http://localhost:8080/login/oauth2/code/example-client
    &code=AUTHORIZATION_CODE


### 3. Obtain Authorization Code (Authorization Code with PKCE)
GET http://localhost:9000/oauth2/authorize
Content-Type: application/x-www-form-urlencoded

client_id=example-client
    &redirect_uri=http://localhost:8080/login/oauth2/code/example-client
    &response_type=code
    &scope=user:manage
    &code_challenge=12354     # Replace with your generated code_challenge
    &code_challenge_method=S256